### ISSUE TITLE
Meteor 1.0.4 issues

### ISSUE THREAD

**Issue by mewm** [peerlibrary/meteor-server-autorun#2]
When this package is installed on Meteor 1.0.4 the client loads forever in the browser.

**Comment by mitar** [comment]
This package is modifying only the sever side?

**Comment by cherbst** [comment]
I think this commit fixes the issue:
https://github.com/cherbst/meteor-server-autorun/commit/86609ceb60659d9ace9e7a43ea23d230de7549da

**Comment by mewm** [comment]
@mitar I know, that's why I don't understand why this was/is happening. 
@cherbst okay cool, I'll try it out again eventually.

**Comment by larixer** [comment]
I confirm, that the commit above fixes "client loading forever" issue for me.

However, server tracker still doesn't work smoothly. I need to localize the next problem to make the report, but in few words - the client page showing records from database, that were populated inside server tracker, keeps re-rendering all the time. Not sure whether this connected with above fix or whether it is completely different problem.
