### ISSUE TITLE
finds and findOnes don't work right?

### ISSUE THREAD

**Issue by rclai** [peerlibrary/meteor-server-autorun#7]
I tried doing this:

``` js
Tracker.autorun(function () {
  console.log('there are', Test.find().count(), 'test items')
});
```

While I inserted items into the `Test` collection in the Meteor shell, but the `console.log` didn't re-log again.

**Comment by mitar** [comment]
They work for local collections (Minimongo), but server-side cursor for MongoDB are not reactive by itself.

There is an idea to make them so with a package, but it is not yet there.

As a workaround you can make an observe which copies into a local collection from MongoDB, and then use queries on that local collection. For some cases it works well. :-)

**Comment by rclai** [comment]
Oh interesting.. haha.

**Comment by aramk** [comment]
I had the same issue and used `cursor.observe()` instead of Tracker. I have a wrapper in [my library](https://github.com/urbanetic/meteor-utility/blob/master/src/Collections.coffee#L137) so I can handle all changes with a single callback:

```
Collections.observe Events.getCollection(), onEventChange
Collections.observe UserEvents.getCollection(), onEventChange
```

`ReactiveVar` still triggers changes in `Tracker.autorun()` with this library though.

**Comment by mitar** [comment]
In meantime we developed [reactive-mongo](https://github.com/peerlibrary/meteor-reactive-mongo) package which provides reactive server-side MongoDB queries, and also [reactive-publish](https://github.com/peerlibrary/meteor-reactive-publish) which provides full server-side reactive publish endpoints.

**Comment by aramk** [comment]
Very handy!
